namespace WebTestToolkit.Contracts.Models;

// One captured, user-labeled action in a flow. Label drives the Gherkin step text directly
// (the user types it while inspecting) — nothing here is generated by an LLM.
public class TestStep
{
    public int Order { get; set; }
    public ActionType ActionType { get; set; }
    public string Label { get; set; } = "";
    public string PageName { get; set; } = "";
    public string LocatorKey { get; set; } = "";
    public CapturedElement? Element { get; set; }
    public string? InputValue { get; set; }
    public string? ExpectedText { get; set; }
}
